from pyatspi.utils import *
from pyatspi.interface import *
from _typeshed import Incomplete

__all__ = ['Action']

class Action(interface):
    def getActions(self): ...
    def doAction(self, index): ...
    def getDescription(self, index): ...
    def getKeyBinding(self, index): ...
    def getName(self, index): ...
    def getLocalizedName(self, index): ...
    def get_nActions(self): ...
    nActions: Incomplete
