from _typeshed import Incomplete
from pyatspi.utils import *

__all__ = ['Application']

class Application:
    obj: Incomplete
    def __init__(self, obj) -> None: ...
    def getLocale(self, locale_type) -> None: ...
    def get_id(self): ...
    id: Incomplete
    def get_toolkitName(self): ...
    toolkitName: Incomplete
    def get_version(self): ...
    version: Incomplete
