from pyatspi.interface import *
from pyatspi.utils import *

__all__ = ['Document']

class Document(interface):
    def getAttributeValue(self, key): ...
    def getAttributes(self): ...
    def getLocale(self): ...
    def getCurrentPageNumber(self): ...
    def getPageCount(self): ...
