from pyatspi.text import *
from pyatspi.utils import *

__all__ = ['EditableText']

class EditableText(Text):
    def copyText(self, start, end): ...
    def cutText(self, start, end): ...
    def deleteText(self, start, end): ...
    def insertText(self, position, text, length): ...
    def pasteText(self, position): ...
    def setTextContents(self, contents): ...
