from pyatspi.interface import *
from pyatspi.utils import *

__all__ = ['Hypertext']

class Hypertext(interface):
    def getLink(self, index): ...
    def getLinkIndex(self, character_index): ...
    def getNLinks(self): ...
