from pyatspi.utils import *
from _typeshed import Incomplete

__all__ = ['Image']

class Image:
    obj: Incomplete
    def __init__(self, obj) -> None: ...
    def getImageExtents(self, coordType): ...
    def getImagePosition(self, coord_type): ...
    def getImageSize(self): ...
    def get_imageDescription(self): ...
    imageDescription: Incomplete
    def get_imageLocale(self): ...
    imageLocale: Incomplete
