from _typeshed import Incomplete

__all__ = ['Registry', 'MAIN_LOOP_GLIB', 'MAIN_LOOP_NONE', 'set_default_registry']

MAIN_LOOP_GLIB: str
MAIN_LOOP_NONE: str

class Registry:
    __dict__: Incomplete
    has_implementations: bool
    app_event_register: Incomplete
    desktop: Incomplete
    main_loop: Incomplete
    def __init__(self) -> None: ...
    def __call__(self): ...
    def __getattr__(self, name): ...
    asynchronous: Incomplete
    def __setattr__(self, name, value) -> None: ...
    started: bool
    def start(self, asynchronous: bool = False, gil: bool = True, **kwargs): ...
    def stop(self, *args) -> None: ...
    def getDesktopCount(self): ...
    def getDesktop(self, i): ...
    def eventWrapper(self, event, callback): ...
    def registerEventListener(self, client, *names) -> None: ...
    def registerEventListenerWithApp(self, client, app, *names) -> None: ...
    def deregisterEventListener(self, client, *names) -> None: ...
    def makeSyncType(self, synchronous, preemptive, global_): ...
    def makeKind(self, kind): ...
    def registerKeystrokeListener(self, client, key_set=[], mask: int = 0, kind=..., synchronous: bool = True, preemptive: bool = True, global_: bool = False) -> None: ...
    def deregisterKeystrokeListener(self, client, key_set=[], mask: int = 0, kind=...) -> None: ...
    def generateKeyboardEvent(self, keycode, keysym, kind) -> None: ...
    def generateMouseEvent(self, x, y, name) -> None: ...
    def setReferenceWIndow(accessible) -> None: ...
    def pumpQueuedEvents(self) -> None: ...

def set_default_registry(main_loop, app_name=None) -> None: ...
