from _typeshed import Incomplete
from pyatspi.atspienum import *

class Role(AtspiEnum): ...

ROLE_ACCELERATOR_LABEL: Incomplete
ROLE_ALERT: Incomplete
ROLE_ANIMATION: Incomplete
ROLE_APPLICATION: Incomplete
ROLE_ARROW: Incomplete
ROLE_ARTICLE: Incomplete
ROLE_AUDIO: Incomplete
ROLE_AUTOCOMPLETE: Incomplete
ROLE_BLOCK_QUOTE: Incomplete
ROLE_CALENDAR: Incomplete
ROLE_CANVAS: Incomplete
ROLE_CAPTION: Incomplete
ROLE_CHART: Incomplete
ROLE_CHECK_BOX: Incomplete
ROLE_CHECK_MENU_ITEM: Incomplete
ROLE_COLOR_CHOOSER: Incomplete
ROLE_COLUMN_HEADER: Incomplete
ROLE_COMBO_BOX: Incomplete
ROLE_COMMENT: Incomplete
ROLE_CONTENT_DELETION: Incomplete
ROLE_CONTENT_INSERTION: Incomplete
ROLE_DATE_EDITOR: Incomplete
ROLE_DEFINITION: Incomplete
ROLE_DESCRIPTION_LIST: Incomplete
ROLE_DESCRIPTION_TERM: Incomplete
ROLE_DESCRIPTION_VALUE: Incomplete
ROLE_DESKTOP_FRAME: Incomplete
ROLE_DESKTOP_ICON: Incomplete
ROLE_DIAL: Incomplete
ROLE_DIALOG: Incomplete
ROLE_DIRECTORY_PANE: Incomplete
ROLE_DOCUMENT_EMAIL: Incomplete
ROLE_DOCUMENT_FRAME: Incomplete
ROLE_DOCUMENT_PRESENTATION: Incomplete
ROLE_DOCUMENT_SPREADSHEET: Incomplete
ROLE_DOCUMENT_TEXT: Incomplete
ROLE_DOCUMENT_WEB: Incomplete
ROLE_DRAWING_AREA: Incomplete
ROLE_EDITBAR: Incomplete
ROLE_EMBEDDED: Incomplete
ROLE_ENTRY: Incomplete
ROLE_EXTENDED: Incomplete
ROLE_FILE_CHOOSER: Incomplete
ROLE_FILLER: Incomplete
ROLE_FOCUS_TRAVERSABLE: Incomplete
ROLE_FONT_CHOOSER: Incomplete
ROLE_FOOTER: Incomplete
ROLE_FOOTNOTE: Incomplete
ROLE_FORM: Incomplete
ROLE_FRAME: Incomplete
ROLE_GLASS_PANE: Incomplete
ROLE_GROUPING: Incomplete
ROLE_HEADER: Incomplete
ROLE_HEADING: Incomplete
ROLE_HTML_CONTAINER: Incomplete
ROLE_ICON: Incomplete
ROLE_IMAGE: Incomplete
ROLE_IMAGE_MAP: Incomplete
ROLE_INFO_BAR: Incomplete
ROLE_INPUT_METHOD_WINDOW: Incomplete
ROLE_INTERNAL_FRAME: Incomplete
ROLE_INVALID: Incomplete
ROLE_LABEL: Incomplete
ROLE_LANDMARK: Incomplete
ROLE_LAST_DEFINED: Incomplete
ROLE_LAYERED_PANE: Incomplete
ROLE_LEVEL_BAR: Incomplete
ROLE_LINK: Incomplete
ROLE_LIST: Incomplete
ROLE_LIST_BOX: Incomplete
ROLE_LIST_ITEM: Incomplete
ROLE_LOG: Incomplete
ROLE_MARK: Incomplete
ROLE_MARQUEE: Incomplete
ROLE_MATH: Incomplete
ROLE_MATH_FRACTION: Incomplete
ROLE_MATH_ROOT: Incomplete
ROLE_MENU: Incomplete
ROLE_MENU_BAR: Incomplete
ROLE_MENU_ITEM: Incomplete
ROLE_NOTIFICATION: Incomplete
ROLE_OPTION_PANE: Incomplete
ROLE_PAGE: Incomplete
ROLE_PAGE_TAB: Incomplete
ROLE_PAGE_TAB_LIST: Incomplete
ROLE_PANEL: Incomplete
ROLE_PARAGRAPH: Incomplete
ROLE_PASSWORD_TEXT: Incomplete
ROLE_POPUP_MENU: Incomplete
ROLE_PUSH_BUTTON_MENU: Incomplete
ROLE_PROGRESS_BAR: Incomplete
ROLE_PUSH_BUTTON: Incomplete
ROLE_RADIO_BUTTON: Incomplete
ROLE_RADIO_MENU_ITEM: Incomplete
ROLE_RATING: Incomplete
ROLE_REDUNDANT_OBJECT: Incomplete
ROLE_ROOT_PANE: Incomplete
ROLE_ROW_HEADER: Incomplete
ROLE_RULER: Incomplete
ROLE_SCROLL_BAR: Incomplete
ROLE_SCROLL_PANE: Incomplete
ROLE_SECTION: Incomplete
ROLE_SEPARATOR: Incomplete
ROLE_SLIDER: Incomplete
ROLE_SPIN_BUTTON: Incomplete
ROLE_SPLIT_PANE: Incomplete
ROLE_STATIC: Incomplete
ROLE_STATUS_BAR: Incomplete
ROLE_SUBSCRIPT: Incomplete
ROLE_SUGGESTION: Incomplete
ROLE_SUPERSCRIPT: Incomplete
ROLE_SWITCH: Incomplete
ROLE_TABLE: Incomplete
ROLE_TABLE_CELL: Incomplete
ROLE_TABLE_COLUMN_HEADER: Incomplete
ROLE_TABLE_ROW: Incomplete
ROLE_TABLE_ROW_HEADER: Incomplete
ROLE_TEAROFF_MENU_ITEM: Incomplete
ROLE_TERMINAL: Incomplete
ROLE_TEXT: Incomplete
ROLE_TIMER: Incomplete
ROLE_TITLE_BAR: Incomplete
ROLE_TOGGLE_BUTTON: Incomplete
ROLE_TOOL_BAR: Incomplete
ROLE_TOOL_TIP: Incomplete
ROLE_TREE: Incomplete
ROLE_TREE_ITEM: Incomplete
ROLE_TREE_TABLE: Incomplete
ROLE_UNKNOWN: Incomplete
ROLE_VIDEO: Incomplete
ROLE_VIEWPORT: Incomplete
ROLE_WINDOW: Incomplete
ROLE_NAMES: Incomplete
