from _typeshed import Incomplete
from pyatspi.interface import *
from pyatspi.utils import *

__all__ = ['Selection']

class Selection(interface):
    def clearSelection(self): ...
    def deselectChild(self, childIndex): ...
    def deselectSelectedChild(self, index): ...
    def getSelectedChild(self, index): ...
    def isChildSelected(self, index): ...
    def selectAll(self): ...
    def selectChild(self, index): ...
    def get_nSelectedChildren(self): ...
    nSelectedChildren: Incomplete
