from _typeshed import Incomplete
from pyatspi.interface import *
from pyatspi.utils import *

__all__ = ['TableCell']

class TableCell(interface):
    def get_columnSpan(self): ...
    columnSpan: Incomplete
    def get_columnHeaderCells(self): ...
    columnHeaderCells: Incomplete
    def get_rowSpan(self): ...
    rowSpan: Incomplete
    def get_rowHeaderCells(self): ...
    rowHeaderCells: Incomplete
    def get_position(self): ...
    position: Incomplete
    def getRowColumnSpan(self): ...
    def get_table(self): ...
    table: Incomplete
