from pyatspi.utils import *
from pyatspi.interface import *
from _typeshed import Incomplete

__all__ = ['Table']

class Table(interface):
    def addColumnSelection(self, column): ...
    def addRowSelection(self, row): ...
    def getAccessibleAt(self, row, column): ...
    def getColumnAtIndex(self, index): ...
    def getColumnDescription(self, column): ...
    def getColumnExtentAt(self, row, column): ...
    def getColumnHeader(self, index): ...
    def getIndexAt(self, row, column): ...
    def getRowAtIndex(self, index): ...
    def getRowColumnExtentsAtIndex(self, index): ...
    def getRowDescription(self, index): ...
    def getRowExtentAt(self, row, column): ...
    def getRowHeader(self, row): ...
    def getSelectedColumns(self): ...
    def getSelectedRows(self): ...
    def isColumnSelected(self, column): ...
    def isRowSelected(self, row): ...
    def isSelected(self, row, column): ...
    def removeColumnSelection(self, column): ...
    def removeRowSelection(self, row): ...
    def get_caption(self): ...
    caption: Incomplete
    def get_nColumns(self): ...
    nColumns: Incomplete
    def get_nRows(self): ...
    nRows: Incomplete
    def get_nSelectedColumns(self): ...
    nSelectedColumns: Incomplete
    def get_nSelectedRows(self): ...
    nSelectedRows: Incomplete
    def get_summary(self): ...
    summary: Incomplete
