from pyatspi.atspienum import *
from pyatspi.utils import *
from pyatspi.interface import *
from _typeshed import Incomplete

__all__ = ['Text', 'TEXT_BOUNDARY_TYPE', 'TEXT_BOUNDARY_CHAR', 'TEXT_BOUNDARY_WORD_START', 'TEXT_BOUNDARY_WORD_END', 'TEXT_BOUNDARY_SENTENCE_START', 'TEXT_BOUNDARY_SENTENCE_END', 'TEXT_BOUNDARY_LINE_START', 'TEXT_BOUNDARY_LINE_END', 'TEXT_CLIP_TYPE', 'TEXT_CLIP_NONE', 'TEXT_CLIP_MIN', 'TEXT_CLIP_MAX', 'TEXT_CLIP_BOTH', 'TEXT_GRANULARITY_CHAR', 'TEXT_GRANULARITY_WORD', 'TEXT_GRANULARITY_SENTENCE', 'TEXT_GRANULARITY_LINE', 'TEXT_GRANULARITY_PARAGRAPH']

class TEXT_BOUNDARY_TYPE(AtspiEnum): ...

TEXT_BOUNDARY_CHAR: Incomplete
TEXT_BOUNDARY_LINE_END: Incomplete
TEXT_BOUNDARY_LINE_START: Incomplete
TEXT_BOUNDARY_SENTENCE_END: Incomplete
TEXT_BOUNDARY_SENTENCE_START: Incomplete
TEXT_BOUNDARY_WORD_END: Incomplete
TEXT_BOUNDARY_WORD_START: Incomplete

class TEXT_CLIP_TYPE(AtspiEnum): ...

TEXT_CLIP_BOTH: Incomplete
TEXT_CLIP_MAX: Incomplete
TEXT_CLIP_MIN: Incomplete
TEXT_CLIP_NONE: Incomplete

class TEXT_GRANULARITY_TYPE(AtspiEnum): ...

TEXT_GRANULARITY_CHAR: Incomplete
TEXT_GRANULARITY_WORD: Incomplete
TEXT_GRANULARITY_SENTENCE: Incomplete
TEXT_GRANULARITY_LINE: Incomplete
TEXT_GRANULARITY_PARAGRAPH: Incomplete

class Text(interface):
    def addSelection(self, startOffset, endOffset): ...
    def getAttributeRun(self, offset, includeDefaults: bool = True): ...
    def getAttributeValue(self, offset, attributeName): ...
    def getAttributes(self, offset): ...
    def getBoundedRanges(self, x, y, width, height, coordType, xClipType, yClipType): ...
    def getCharacterAtOffset(self, offset): ...
    def getCharacterExtents(self, offset, coordType): ...
    def getDefaultAttributeSet(self): ...
    def getDefaultAttributes(self): ...
    def getNSelections(self): ...
    def getOffsetAtPoint(self, x, y, coordType): ...
    def getRangeExtents(self, startOffset, endOffset, coordType): ...
    def getSelection(self, selectionNum): ...
    def getText(self, startOffset, endOffset): ...
    def getTextAfterOffset(self, offset, type): ...
    def getTextAtOffset(self, offset, type): ...
    def getTextBeforeOffset(self, offset, type): ...
    def getStringAtOffset(self, offset, type): ...
    def removeSelection(self, selectionNum): ...
    def setCaretOffset(self, offset): ...
    def setSelection(self, selectionNum, startOffset, endOffset): ...
    def get_caretOffset(self): ...
    caretOffset: Incomplete
    def get_characterCount(self): ...
    characterCount: Incomplete
    def scrollSubstringTo(self, startOffset, endOffset, scroll_type): ...
    def scrollSubstringToPoint(self, startOffset, endOffset, coord_type, x, y): ...
