from _typeshed import Incomplete
from pyatspi.deviceevent import allModifiers as allModifiers

__all__ = ['setCacheLevel', 'getCacheLevel', 'clearCache', 'printCache', 'getInterfaceIID', 'getInterfaceName', 'listInterfaces', 'stringToConst', 'stateToString', 'relationToString', 'allModifiers', 'findDescendant', 'findAllDescendants', 'findAncestor', 'getPath', 'pointToList', 'rectToList', 'attributeListToHash', 'hashToAttributeList', 'getBoundingBox']

def setCacheLevel(level) -> None: ...
def getCacheLevel() -> None: ...
def clearCache() -> None: ...
def printCache() -> None: ...
def getInterfaceIID(obj): ...
def getInterfaceName(obj): ...
def listInterfaces(obj): ...
def stringToConst(prefix, suffix): ...
def stateToString(value): ...
def relationToString(value): ...
def findDescendant(acc, pred, breadth_first: bool = False): ...
def findAllDescendants(acc, pred): ...
def findAncestor(acc, pred): ...
def getPath(acc): ...
def pointToList(point): ...
def rectToList(rect): ...
def attributeListToHash(list): ...
def hashToAttributeList(h): ...

class BoundingBox(list):
    def __new__(cls, x, y, width, height): ...
    def __init__(self, x, y, width, height) -> None: ...
    x: Incomplete
    y: Incomplete
    width: Incomplete
    height: Incomplete

def getBoundingBox(rect): ...
