from _typeshed import Incomplete
from pyatspi.interface import *
from pyatspi.utils import *

__all__ = ['Value']

class Value(interface):
    def get_currentValue(self): ...
    def set_currentValue(self, value) -> None: ...
    currentValue: Incomplete
    def get_maximumValue(self): ...
    maximumValue: Incomplete
    def get_minimumIncrement(self): ...
    minimumIncrement: Incomplete
    def get_minimumValue(self): ...
    minimumValue: Incomplete
